### ISSUE TITLE
In Grunt file,  what is the difference between: grunt --verbose y grunt (default)

### ISSUE THREAD

**Issue by jlcallalle** [vtex/speed#41]
Hi, Team VTEX
In Grunt file,  what is the difference between: grunt --verbose y grunt (default)
another do you recommend to user gulp with grunt?
because I want to add script gulp  for create workflow sass modules

thanks

**Comment by klzns** [comment]
> In Grunt file, what is the difference between: grunt --verbose y grunt (default)

That's a grunt feature to log more information to the console. You can read its documentation here:
https://gruntjs.com/using-the-cli#verbose-v

<br/>

> another do you recommend to user gulp with grunt?

I don't recommend because both can do pretty much the same thing. But, if you're liking gulp more that's doable too.


<br/>
About Sass modules you can setup grunt to do that. I wrote about it here:
https://github.com/vtex/speed/issues/23#issuecomment-218031490
