### ISSUE TITLE
Use vtex speed through external company proxy

### ISSUE THREAD

**Issue by gandalfmza** [vtex/speed#52]
**Você quer pedir uma nova feature ou reportar um bug?**
Im trying to use vtex speed through the company internet connection that has proxy.

**Qual o comportamento atual?**
I receive the error "ETIMEDOUT" on console when trying to connect to vtexlocal.

**Se o comportamento atual é um bug, por favor, forneça os passos para reproduzir o problema.**
Console: 
npm run start
Browser:
******.vtexlocal.com.br
Result:
Console
"ETIMEDOUT /"

**Qual o comportamento esperado?**
Succefully connection to vtexlocal.com.br

**Qual browser e sistema operacional são afetados por esse problema?**
Running Grunt on Windows

**Comment by klzns** [comment]
@gandalfmza are you using the latest version of VTEX Speed?

**Comment by gandalfmza** [comment]
@klzns  Yes, it works using 3G or in my house.

**Comment by klzns** [comment]
@gandalfmza I don't know what changes you would have to make to make it work.

Maybe it's your proxy that needs to implement things like to unpack HTTPS:

https://github.com/vtex/speed/blob/master/speed-middleware.coffee#L31-L32
https://github.com/vtex/speed/blob/master/speed-middleware.coffee#L44-L45

I'm closing the issue since it's not a Speed issue.

Feel free to share you solution on this issue though, it might help someone else.
